import image from "../assets/img/our_project.png";

export const dataFile = [
  {
    id: 1,
    filename: "Titre 1",
    content: "Lorem Ipsum",
    createdAt: "7 Juin 2023",
    image: image,
    isPublic: true,
  },

  {
    id: 2,
    filename: "Titre 2",
    content: "Lorem Ipsum",
    createdAt: "7 Juin 2023",
    image: image,
    isPublic: true,
  },
  {
    id: 3,
    filename: "Titre 3",
    content: "Lorem Ipsum",
    createdAt: "7 Juin 2023",
    image: image,
    isPublic: true,
  },
  {
    id: 4,
    filename: "Titre 4",
    content: "Lorem Ipsum",
    createdAt: "7 Juin 2023",
    image: image,
    isPublic: true,
  },
  {
    id: 4,
    filename: "Titre 4",
    content: "Lorem Ipsum",
    createdAt: "7 Juin 2023",
    image: image,
    isPublic: true,
  },
  {
    id: 5,
    filename: "Titre 5",
    content: "Lorem Ipsum",
    createdAt: "7 Juin 2023",
    image: image,
    isPublic: true,
  },
  {
    id: 6,
    filename: "Titre 6",
    content: "Lorem Ipsum",
    createdAt: "7 Juin 2023",
    image: image,
    isPublic: false,
  },
  {
    id: 7,
    filename: "Titre 7",
    content: "Lorem Ipsum",
    createdAt: "7 Juin 2023",
    image: image,
    isPublic: true,
  },
  {
    id: 8,
    filename: "Titre 8",
    content: "Lorem Ipsum",
    createdAt: "7 Juin 2023",
    image: image,
    isPublic: false,
  },
  {
    id: 9,
    filename: "Titre 9",
    content: "Lorem Ipsum",
    createdAt: "7 Juin 2023",
    image: image,
    isPublic: false,
  },
  {
    id: 10,
    filename: "Titre 10",
    content: "Lorem Ipsum",
    createdAt: "7 Juin 2023",
    image: image,
    isPublic: false,
  },
  {
    id: 11,
    filename: "Titre 11",
    content: "Lorem Ipsum",
    createdAt: "7 Juin 2023",
    image: image,
    isPublic: false,
  },
];
